### ISSUE TITLE
打卡失败，求助

### ISSUE THREAD

**Issue by Gahotx** [weixiabing/hdu-health-sign-in#2]
大佬你好，我添加了secret，USERNAME和PASSWORD，并且可以确定是易班账号密码没问题了，但是还是打卡失败，请问是为什么？和我没有添加TG_TOKEN，CHAT_ID有关吗？因为我不用tg，就没有添加了。
![image](https://user-images.githubusercontent.com/53534938/134115537-181a26c8-0e5c-4203-895d-6d5178acd333.png)
![image](https://user-images.githubusercontent.com/53534938/134115281-af424fad-7d35-4af2-b612-b5e71e69d1d9.png)

**Comment by weixiabing** [comment]
还有一点小问题等我解决一下
单账号应该问题不大
因为是完成打卡后再发通知的

**Comment by weixiabing** [comment]
我也挺奇怪的因为前天还能用今天就不太行了

**Comment by weixiabing** [comment]
问题很大，杭电助手把定位不准手动定位这个按钮取消了
脚本用不了了

**Comment by Gahotx** [comment]
不是还有吗？
<img src="https://user-images.githubusercontent.com/53534938/134161505-cf8e8e69-2328-417c-b5c1-0f91467e8816.jpg" width="50%"><img src="https://user-images.githubusercontent.com/53534938/134161524-4a204616-85b4-403c-80b0-3953c8e563a4.jpg" width=50%>

**Comment by weixiabing** [comment]
emmmm 我怎么没了真奇怪
明天打卡重置了我再看看

**Comment by Gahotx** [comment]
嗯嗯，除了代码之外有需要帮忙测试之类的阔以dd我![M~~4Q%J1 V9%SN53T$F1{LP](https://user-images.githubusercontent.com/53534938/134198455-251227bb-0349-48c4-b8dc-a3669352b06c.png)

**Comment by weixiabing** [comment]
好

**Comment by weixiabing** [comment]
你测试一下今天能不能用
我今天有个号打上卡了

**Comment by Gahotx** [comment]
不知道为什么，今天早上好了
<img src="https://user-images.githubusercontent.com/53534938/134273543-13f04499-7b7b-49aa-96e0-9cef29ae96e5.jpg" width="50%">

**Comment by weixiabing** [comment]
有点玄学了
和sleep()的时间和github服务器有点关系吧
再测试几天再说
我早上没打上后来又运行了一次才成功
果然玄学
